"""external pressure addition

Revision ID: 23a4467faf0d
Revises: 67f2bd6f7623
Create Date: 2026-04-06 11:13:41.533646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23a4467faf0d'
down_revision: Union[str, Sequence[str], None] = '67f2bd6f7623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_device_readings', sa.Column('external_pressure', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_device_readings', 'external_pressure')
    # ### end Alembic commands ###
