"""add user_id to researcher_requests

Revision ID: 4dc864031b54
Revises: 6dc280d13de3
Create Date: 2026-04-04 14:06:03.325369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4dc864031b54'
down_revision: Union[str, Sequence[str], None] = '6dc280d13de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # --- device_clusters: make status NOT NULL ---
    op.alter_column(
        'device_clusters', 'status',
        existing_type=postgresql.ENUM(
            'APPROVED', 'REJECTED', 'PENDING', name='status'
        ),
        nullable=False,
    )

    # --- devices: drop old named FK then recreate without ON DELETE ---
    device_fks = {
        fk['name']
        for fk in inspector.get_foreign_keys('devices')
    }
    if 'fk_devices_cluster_id_device_clusters' in device_fks:
        op.drop_constraint(
            'fk_devices_cluster_id_device_clusters',
            'devices', type_='foreignkey',
        )
    # Drop any remaining unnamed FK on devices.cluster_id -> device_clusters
    for fk in inspector.get_foreign_keys('devices'):
        if (
            fk.get('referred_table') == 'device_clusters'
            and 'cluster_id' in fk.get('constrained_columns', [])
            and fk['name'] not in ('fk_devices_cluster_id_device_clusters',)
            and fk['name'] not in device_fks - {'fk_devices_cluster_id_device_clusters'}
        ):
            op.drop_constraint(fk['name'], 'devices', type_='foreignkey')

    op.create_foreign_key(
        None, 'devices', 'device_clusters', ['cluster_id'], ['id'],
    )

    # --- researcher_requests: make user_id and status NOT NULL ---
    rr_cols = {c['name'] for c in inspector.get_columns('researcher_requests')}
    if 'user_id' in rr_cols:
        op.alter_column(
            'researcher_requests', 'user_id',
            existing_type=sa.INTEGER(),
            nullable=False,
        )
    op.alter_column(
        'researcher_requests', 'status',
        existing_type=postgresql.ENUM(
            'PENDING', 'APPROVED', 'REJECTED', name='researcherrequeststatus'
        ),
        nullable=False,
    )

    # Drop email index if present
    rr_indexes = {ix['name'] for ix in inspector.get_indexes('researcher_requests')}
    if 'ix_researcher_requests_email' in rr_indexes:
        op.drop_index('ix_researcher_requests_email', table_name='researcher_requests')

    # Drop named FKs on researcher_requests if they exist, then recreate
    rr_fks = {fk['name']: fk for fk in inspector.get_foreign_keys('researcher_requests')}
    if 'fk_researcher_requests_user_id_users' in rr_fks:
        op.drop_constraint(
            'fk_researcher_requests_user_id_users',
            'researcher_requests', type_='foreignkey',
        )
    if 'fk_researcher_requests_cluster_id_device_clusters' in rr_fks:
        op.drop_constraint(
            'fk_researcher_requests_cluster_id_device_clusters',
            'researcher_requests', type_='foreignkey',
        )

    # Refresh FK state after drops
    rr_fks_after = {
        (tuple(fk['constrained_columns']), fk['referred_table'])
        for fk in inspector.get_foreign_keys('researcher_requests')
    }
    if (('user_id',), 'users') not in rr_fks_after:
        op.create_foreign_key(
            None, 'researcher_requests', 'users', ['user_id'], ['id'],
        )
    if (('cluster_id',), 'device_clusters') not in rr_fks_after:
        op.create_foreign_key(
            None, 'researcher_requests', 'device_clusters', ['cluster_id'], ['id'],
        )

    # Drop old columns if they still exist
    rr_cols_now = {c['name'] for c in inspector.get_columns('researcher_requests')}
    for col in ('first_name', 'research_purpose', 'last_name', 'institution', 'email', 'approval_status'):
        if col in rr_cols_now:
            op.drop_column('researcher_requests', col)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('researcher_requests', sa.Column('approval_status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus'), autoincrement=False, nullable=False))
    op.add_column('researcher_requests', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('researcher_requests', sa.Column('institution', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('researcher_requests', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('researcher_requests', sa.Column('research_purpose', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('researcher_requests', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'researcher_requests', type_='foreignkey')
    op.drop_constraint(None, 'researcher_requests', type_='foreignkey')
    op.create_foreign_key(op.f('fk_researcher_requests_cluster_id_device_clusters'), 'researcher_requests', 'device_clusters', ['cluster_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_researcher_requests_user_id_users'), 'researcher_requests', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_researcher_requests_email'), 'researcher_requests', ['email'], unique=True)
    op.alter_column('researcher_requests', 'status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='researcherrequeststatus'),
               nullable=True)
    op.alter_column('researcher_requests', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.create_foreign_key(op.f('fk_devices_cluster_id_device_clusters'), 'devices', 'device_clusters', ['cluster_id'], ['id'], ondelete='SET NULL')
    op.alter_column('device_clusters', 'status',
               existing_type=postgresql.ENUM('APPROVED', 'REJECTED', 'PENDING', name='status'),
               nullable=True)
    # ### end Alembic commands ###
