"""add user_id to researcher_requests

Revision ID: 4dc864031b54
Revises: 6dc280d13de3
Create Date: 2026-04-04 14:06:03.325369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4dc864031b54'
down_revision: Union[str, Sequence[str], None] = '6dc280d13de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device_clusters', 'status',
               existing_type=postgresql.ENUM('APPROVED', 'REJECTED', 'PENDING', name='status'),
               nullable=False)
    op.drop_constraint(op.f('fk_devices_cluster_id_device_clusters'), 'devices', type_='foreignkey')
    op.create_foreign_key(None, 'devices', 'device_clusters', ['cluster_id'], ['id'])
    op.alter_column('researcher_requests', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('researcher_requests', 'status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='researcherrequeststatus'),
               nullable=False)
    op.drop_index(op.f('ix_researcher_requests_email'), table_name='researcher_requests')
    op.drop_constraint(op.f('fk_researcher_requests_user_id_users'), 'researcher_requests', type_='foreignkey')
    op.drop_constraint(op.f('fk_researcher_requests_cluster_id_device_clusters'), 'researcher_requests', type_='foreignkey')
    op.create_foreign_key(None, 'researcher_requests', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'researcher_requests', 'device_clusters', ['cluster_id'], ['id'])
    op.drop_column('researcher_requests', 'first_name')
    op.drop_column('researcher_requests', 'research_purpose')
    op.drop_column('researcher_requests', 'last_name')
    op.drop_column('researcher_requests', 'institution')
    op.drop_column('researcher_requests', 'email')
    op.drop_column('researcher_requests', 'approval_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('researcher_requests', sa.Column('approval_status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus'), autoincrement=False, nullable=False))
    op.add_column('researcher_requests', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('researcher_requests', sa.Column('institution', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('researcher_requests', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('researcher_requests', sa.Column('research_purpose', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('researcher_requests', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'researcher_requests', type_='foreignkey')
    op.drop_constraint(None, 'researcher_requests', type_='foreignkey')
    op.create_foreign_key(op.f('fk_researcher_requests_cluster_id_device_clusters'), 'researcher_requests', 'device_clusters', ['cluster_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_researcher_requests_user_id_users'), 'researcher_requests', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_researcher_requests_email'), 'researcher_requests', ['email'], unique=True)
    op.alter_column('researcher_requests', 'status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='researcherrequeststatus'),
               nullable=True)
    op.alter_column('researcher_requests', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.create_foreign_key(op.f('fk_devices_cluster_id_device_clusters'), 'devices', 'device_clusters', ['cluster_id'], ['id'], ondelete='SET NULL')
    op.alter_column('device_clusters', 'status',
               existing_type=postgresql.ENUM('APPROVED', 'REJECTED', 'PENDING', name='status'),
               nullable=True)
    # ### end Alembic commands ###
