"""create researcher request and cluster

Revision ID: 87696266ee52
Revises: c3337d90d5f1
Create Date: 2026-03-31 17:52:31.080100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87696266ee52'
down_revision: Union[str, Sequence[str], None] = 'c3337d90d5f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOTE:
    # This revision was originally autogenerated while `alembic/env.py` was not importing
    # the app's model modules, leaving `Base.metadata` empty. Alembic therefore generated
    # a destructive "drop everything" migration.
    #
    # It is intentionally a no-op to prevent accidental data loss.
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # No-op; see upgrade() note above.
    pass
