"""add_timestamps_to_device_clusters

Revision ID: fb6ddb4e516d
Revises: 4dc864031b54
Create Date: 2026-04-04 14:31:12.552400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb6ddb4e516d'
down_revision: Union[str, Sequence[str], None] = '4dc864031b54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add as nullable so existing rows don't violate NOT NULL
    op.add_column('device_clusters', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('device_clusters', sa.Column('updated_at', sa.DateTime(), nullable=True))

    # Backfill existing rows with the current timestamp
    op.execute("UPDATE device_clusters SET created_at = NOW(), updated_at = NOW() WHERE created_at IS NULL")

    # Now enforce NOT NULL
    op.alter_column('device_clusters', 'created_at', nullable=False)
    op.alter_column('device_clusters', 'updated_at', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_clusters', 'updated_at')
    op.drop_column('device_clusters', 'created_at')
    # ### end Alembic commands ###
