from enum import StrEnum


class NotificationSeverity(StrEnum):
    INFO = "INFO"
    SUCCESS = "SUCCESS"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class NotificationCategory(StrEnum):
    MOSQUITO = "MOSQUITO"
    SENSOR = "SENSOR"
    DEVICE = "DEVICE"
    ACCOUNT = "ACCOUNT"
    RESEARCH = "RESEARCH"
    CLUSTER = "CLUSTER"
    SYSTEM = "SYSTEM"


class NotificationType(StrEnum):
    SPECIES_DETECTED = "SPECIES_DETECTED"
    ACTIVITY_SURGE = "ACTIVITY_SURGE"
    LOW_BATTERY = "LOW_BATTERY"
    TRAP_TRIGGERED = "TRAP_TRIGGERED"
    EXTREME_TEMPERATURE = "EXTREME_TEMPERATURE"
    EXTREME_HUMIDITY = "EXTREME_HUMIDITY"
    SENSOR_MALFUNCTION = "SENSOR_MALFUNCTION"
    UNKNOWN_DEVICE = "UNKNOWN_DEVICE"
    INVALID_PAYLOAD = "INVALID_PAYLOAD"
    DEVICE_OFFLINE = "DEVICE_OFFLINE"
    DEVICE_ONLINE = "DEVICE_ONLINE"
    DEVICE_LOCATION_CHANGED = "DEVICE_LOCATION_CHANGED"
    DEVICE_REASSIGNED = "DEVICE_REASSIGNED"
    USER_REGISTERED = "USER_REGISTERED"
    USER_APPROVED = "USER_APPROVED"
    USER_REJECTED = "USER_REJECTED"
    ROLE_CHANGED = "ROLE_CHANGED"
    PASSWORD_RESET = "PASSWORD_RESET"
    RESEARCHER_REQUEST_SUBMITTED = "RESEARCHER_REQUEST_SUBMITTED"
    RESEARCHER_REQUEST_APPROVED = "RESEARCHER_REQUEST_APPROVED"
    RESEARCHER_REQUEST_REJECTED = "RESEARCHER_REQUEST_REJECTED"
    CLUSTER_CREATED = "CLUSTER_CREATED"
    CLUSTER_UPDATED = "CLUSTER_UPDATED"
    CLUSTER_DEVICE_ADDED = "CLUSTER_DEVICE_ADDED"
    CLUSTER_DEVICE_REMOVED = "CLUSTER_DEVICE_REMOVED"
    MAINTENANCE_DUE = "MAINTENANCE_DUE"
    DAILY_SUMMARY = "DAILY_SUMMARY"
    WEEKLY_SUMMARY = "WEEKLY_SUMMARY"
    TEST = "TEST"


class PushProvider(StrEnum):
    WEBPUSH = "WEBPUSH"
    FCM = "FCM"
    APNS = "APNS"


class DeliveryChannel(StrEnum):
    PUSH = "PUSH"
    EMAIL = "EMAIL"


class DeliveryStatus(StrEnum):
    PENDING = "PENDING"
    SENT = "SENT"
    FAILED = "FAILED"
